plugins:
  - jest
env:
  es6: true
  node: true
  jest/globals: true
extends:
  - airbnb-base
  - prettier
rules:
  arrow-body-style:
    - error
    - as-needed
  array-bracket-spacing:
    - error
    - never
    - arraysInArrays: true
  comma-spacing:
    - warn
  func-names:
    - warn
  key-spacing:
    - error
    - mode: minimum
  linebreak-style:
    - error
    - unix
  no-alert:
    - warn
  no-console:
    - warn
  no-debugger:
    - warn
  no-extra-semi:
    - error
  no-param-reassign:
    - error
    - props: false
  no-plusplus:
    - 0
  no-restricted-syntax:
    - warn
  no-tabs:
    - 0
  no-trailing-spaces:
    - warn
    - skipBlankLines: true
  no-undef:
    - error
  no-unreachable:
    - error
  no-unused-vars:
    - error
  no-use-before-define:
    - error
    - nofunc
  no-var:
    - warn
  object-curly-spacing:
    - warn
  padded-blocks:
    - 0
  prefer-const:
    - error
  prefer-template:
    - error
  quotes:
    - error
    - single
  semi:
    - error
    - always
  strict:
    - warn
    - safe
  template-curly-spacing:
    - warn
  vars-on-top:
    - warn
