config:
  catalog_script_client:
    nameField:
      - sys_scope
      - name
    formats:
      - fileName: ':sys_scope-:name-script-:sys_id.js'
        contentField: script
  sp_widget:
    nameField: name
    formats:
      - fileName: ':name-client_script-:sys_id.js'
        contentField: client_script
      - fileName: ':name-css-:sys_id.css'
        contentField: css
      - fileName: ':name-demo_data-:sys_id.json'
        contentField: demo_data
      - fileName: ':name-link-:sys_id.js'
        contentField: link
      - fileName: ':name-option_schema-:sys_id.json'
        contentField: option_schema
      - fileName: ':name-script-:sys_id.js'
        contentField: script
      - fileName: ':name-template-:sys_id.html'
        contentField: template
  sys_script:
    nameField:
      - collection
      - sys_scope
      - name
    formats:
      - fileName: ':collection-:sys-scope-:name-script-:sys_id.js'
        contentField: script
filePath: ./now
records:
  catalog_script_client: []
  sp_widget:
    - contentField: client_script
      fileName: breadcrumbs-client_script-0fb269305b3212000d7ec7ad31f91ae2.js
    - contentField: css
      fileName: breadcrumbs-css-0fb269305b3212000d7ec7ad31f91ae2.css
    - contentField: demo_data
      fileName: breadcrumbs-demo_data-0fb269305b3212000d7ec7ad31f91ae2.json
    - contentField: link
      fileName: breadcrumbs-link-0fb269305b3212000d7ec7ad31f91ae2.js
    - contentField: option_schema
      fileName: breadcrumbs-option_schema-0fb269305b3212000d7ec7ad31f91ae2.json
    - contentField: script
      fileName: breadcrumbs-script-0fb269305b3212000d7ec7ad31f91ae2.js
    - contentField: template
      fileName: breadcrumbs-template-0fb269305b3212000d7ec7ad31f91ae2.html
  sys_script: []
